CREATE TABLE IF NOT EXISTS Users
(
    id       INTEGER NOT NULL,
    username TEXT NOT NULL UNIQUE,
    password TEXT,
    PRIMARY KEY(id)
);

-- If MySQL
-- ALTER TABLE Users MODIFY COLUMN id BIGINT AUTO_INCREMENT;